### PR TITLE
new residuals functions

### PR DESCRIPTION
**Pull request by mattansb**
Two functions:

1. `residuals.afex_aov` returns residuals in one of the following formats:

- For between-subject only ANOVAs, a vector of residuals.
- For within-subject/mixed design ANOVAs:
    - `model = "multivariate"`: a multivariate residual matrix.
    - `model = "univariate"`: a list of residuals, with a vector for each of the ANOVA model's error-terms.

2. `residuals_qqplot` returns a ggplot2 qqplot.

(added examples and tests)

### CODE REVIEW

**Comment by mattansb** [comment]
Hi @singmann,
Have you had a chance to look at these? (No pressure, just wondering 😄 )

**Comment by mattansb** [comment]
At a second glance, the within-subjects residuals currently do not account for and continuous covariates - should they?

**Comment by singmann** [comment]
A few things:

- The current version fails `R CMD ckeck` (see: https://travis-ci.org/singmann/afex/jobs/533210490): `residuals.afex_aov.Rd:25: unexpected TEXT ' ', expecting '{'` 
- I am not super happy with the current interface or return value. A common way to use the residuals function is to add them back to the original data.frame to use them later on as shown in the following code (it is maybe not super sensible, but illustrates the issue).
  ```
  df <- data.frame(weight = c(4.17,5.58,5.18,6.11,4.50,4.61,5.17,4.53,5.33,5.14,
                              4.81,4.17,4.41,3.59,5.87,3.83,6.03,4.89,4.32,4.69),
                   group = gl(2, 10, 20, labels = c("Ctl","Trt")))
  lm.D9 <- lm(weight ~ group, df)
  df$residuals <- residuals(lm.D9)
  df$fitted <- fitted(lm.D9)
  plot(fitted ~ residuals, df) 
  ```
  Note that afex' ANOVA function always work with data in the long format. The important conceptual thing seems to be that residuals are mapped to individual data points and the residuals functions has to be able to retain this mapping. Thus, I think it is important that the function is able to return the residuals in the long format retaining the order the original data has. Of course, this is only possible if the ANOVA did not automatically aggregate multiple observations per cell and unit of observation. To make this clear I think it might be a good idea to add a flag or attribute that encodes whether or not data where aggregated automatically. More precisely, I feel like the following code needs to work:
  ```
  library("afex")
  data(md_12.1)
  ma <- aov_ez("id", "rt", md_12.1, within = c("angle", "noise"))
  md_12.1$residuals <- residuals(ma)
  ```
  In addition, there needs to be a way to sensibly deal with the following case in which automatic aggregation takes place:
  ```
  ma2 <- aov_ez("id", "rt", md_12.1, within = c("angle"))
  residuals(ma2)
  ```
  
  In this case, it cannot be added back to the original data, but note that `ma2` now contains the data in long format in `ma2$data$long`. Maybe one can add an argument `return_df` which defaults to `FALSE`, but if `TRUE` returns the long data with an additional column `residuals` which then contains the residuals in the corresponding order.

- Finally, I am not super happy with the name of the plotting function. Actually, I am not sure if this functions is really necessary if we get the residuals (and potentially `fitted`) method to work as in the remainder of `R` modeling function. 

I know that what I say here goes quite beyond what you offer here, but I think if a `residuals` method is added to `afex` it should be integrated into the `R` modelling infrastructure. Let me know if thi sis something you are interested in implementing.

In any case, I am happy if the method focuses on the `lm` slot. As I said, I want to retire the `aov` slot eventually.

**Comment by mattansb** [comment]
I think I addressed all the points you brought up (stayed clear of the `aov` slot).
If you don't think the plotting function belongs here, I would be happy to implement it elsewhere - no worries (:

**Comment by singmann** [comment]
Unfortunately, it does not yet address the case in which the input data is ordered differently then the data used for fitting (which will of course happen in real life). I think this is not a trivial issue to solve. See:

```
data(md_12.1)
md2 <- md_12.1[ sample(seq_len(nrow(md_12.1))), ]
all.equal(md_12.1, md2) ## not TRUE

ma <- aov_ez("id", "rt", md_12.1, within = c("angle", "noise"))
ma2 <- aov_ez("id", "rt", md2, within = c("angle", "noise"))

all.equal(ma, ma2) ## TRUE
all.equal(residuals(ma), residuals(ma2))  ## TRUE, but should not
```

I guess the `afex_aov` objects need some way to remember the original order of the rows relative to the data used for fitting (so objects based on different data will not be the same anymore). I am not sure how to get this though.

**Comment by mattansb** [comment]
Ah, I didn't consider that... In that case, this does seem harder than I thought to implement. I think I will leave this to you (:

**Comment by singmann** [comment]
I know that it is unfortunately not trivial. I will think more about whether or not it is really important to allow adding the residuals back to the original data. Maybe if one adds a clear warning that it can only be used with the `data$long` slot it can work out. Then at least one can link it back to the fitted data, even though it is not in the original form.

And sorry for being so slow in responding to your help with `afex`.

**Comment by mattansb** [comment]
Let me know, after you've thought this through, if there's anything I can do. Otherwise - thanks for this awesome package and for you patience!

**Comment by singmann** [comment]
;aybe a good possibility is to make `afex` compatible with [`ggResidpanel`](https://cran.r-project.org/package=ggResidpanel). Either by adding support for `afex_aov` objects to that package or providing the corresponding methods here. If you are interested to implement this, I could host the necessary support here in `afex`. However, in any case I would not want this as a hard dependency (so only SUGGESTS, no IMPORTS or DEPENDS). Let me know what you think.

**Comment by mattansb** [comment]
Is it a problem that `ggResidpanel` [doesn't use methods](https://github.com/goodekat/ggResidpanel/blob/master/R/resid_panel.R) for different models type?

**Comment by singmann** [comment]
Hmm, that is quite unfortunate. It seems like a problem. But then the vignette specifically provides the possibility to support other model objects (at the very end). Not sure what would be a good way forward. We could maybe ask the authors to make it an S3 generic, or we could provide a function that wraps their code. What do you think? 

Again, my main interest is adding something that is rather general and works in a wide set of circumstances.

**Comment by mattansb** [comment]
Actually, using my suggested `residuals()` function as it is now works, as such:

``` r
library(afex)
library(ggResidpanel)

data(obk.long, package = "afex")
mixed <- aov_car(value ~ treatment * gender + Error(id/(phase*hour)), data = obk.long)
#> Contrasts set to contr.sum for the following variables: treatment, gender

X <- residuals(mixed, return_df = TRUE)
X$predicted <- X[[ncol(X)-1]] - X$residuals

resid_auxpanel(X$residuals,
               X$predicted)
#> Warning: Removed 1 rows containing missing values (geom_bar).
```



<sup>Created on 2019-06-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

However, these would only present model-wise residuals, which seems to be for some reason standard practice (and not nested / projected residuals as I fist suggested way back when).

**Comment by mattansb** [comment]
Back at this a bit again.
Made sure the resulting vector correspond to the rows of `object$data$long`.
It would be ideal to add an attribute in `aov_car` that corresponds to whether any changes in the rows (re order / aggregate) has happened to the input data. This attribute could then be used to give a warning in `residuals.afex_aov`, but I'm not familiar enough with the internal workings of `aov_car` to do this myself.


``` r
library(afex)

### Setup ANOVAs
data(obk.long, package = "afex")
between <- aov_car(value ~ treatment*gender + Error(id), data = obk.long)
#> Warning: More than one observation per cell, aggregating the data using mean
#> (i.e, fun_aggregate = mean)!
#> Contrasts set to contr.sum for the following variables: treatment, gender
within <- aov_car(value ~ 1 + Error(id/(phase*hour)), data = obk.long)
mixed <- aov_car(value ~ treatment * gender + Error(id/(phase*hour)), data = obk.long)
#> Contrasts set to contr.sum for the following variables: treatment, gender

# Residuals
residuals(within)
#>   [1] -4.0625 -3.2500 -5.8125 -2.3125 -1.4375 -2.0625 -3.5625 -1.8750 -3.3750
#>  [10] -2.8750 -2.8125 -2.1875 -1.3125 -2.5000 -3.0625  1.9375  1.7500  1.1875
#>  [19]  0.6875  2.5625  0.9375  1.4375 -0.8750  1.6250  3.1250  0.1875 -0.1875
#>  [28] -0.3125 -1.5000 -0.0625 -1.0625 -0.2500  0.1875 -0.3125 -0.4375 -0.0625
#>  [37] -1.5625  0.1250 -1.3750 -0.8750 -0.8125 -1.1875 -1.3125 -2.5000 -1.0625
#>  [46]  1.9375  0.7500  2.1875  1.6875  1.5625  3.9375  4.4375  4.1250  2.6250
#>  [55]  1.1250  2.1875  2.8125  2.6875  1.5000 -1.0625  0.9375  0.7500  0.1875
#>  [64]  3.6875  2.5625 -1.0625  0.4375 -0.8750  1.6250  1.1250  1.1875  0.8125
#>  [73]  0.6875  3.5000  1.9375 -0.0625  0.7500  0.1875 -0.3125 -2.4375 -0.0625
#>  [82]  0.4375  0.1250 -1.3750 -2.8750 -1.8125 -2.1875 -2.3125 -3.5000 -2.0625
#>  [91]  0.9375  0.7500  0.1875 -0.3125  1.5625  0.9375  0.4375  0.1250  2.6250
#> [100]  2.1250 -1.8125 -2.1875 -2.3125 -0.5000 -0.0625  0.9375  1.7500  2.1875
#> [109]  1.6875  1.5625  1.9375  1.4375  1.1250 -0.3750  2.1250  0.1875  0.8125
#> [118]  1.6875  0.5000 -0.0625 -2.0625 -1.2500 -1.8125 -2.3125 -4.4375 -3.0625
#> [127] -3.5625 -3.8750 -1.3750 -1.8750  0.1875 -0.1875 -0.3125 -1.5000 -0.0625
#> [136]  0.9375 -0.2500  1.1875  0.6875  0.5625 -1.0625 -0.5625  0.1250 -1.3750
#> [145] -0.8750  1.1875  1.8125 -0.3125  2.5000  2.9375 -2.0625 -2.2500 -2.8125
#> [154] -3.3125 -1.4375 -3.0625 -3.5625 -3.8750 -1.3750 -1.8750  1.1875 -0.1875
#> [163]  1.6875  0.5000 -0.0625 -2.0625 -3.2500 -1.8125 -2.3125 -2.4375  0.9375
#> [172]  1.4375  1.1250 -0.3750 -1.8750 -0.8125 -0.1875  0.6875 -0.5000 -1.0625
#> [181]  2.9375  3.7500  3.1875  2.6875  0.5625  3.9375  3.4375  3.1250  1.6250
#> [190]  4.1250  3.1875  3.8125  1.6875  4.5000  4.9375  1.9375  2.7500  3.1875
#> [199]  2.6875  2.5625  1.9375  1.4375  1.1250  3.6250  3.1250  1.1875  0.8125
#> [208]  0.6875 -0.5000  0.9375 -0.0625 -0.2500 -0.8125 -1.3125  0.5625 -3.0625
#> [217] -1.5625  1.1250 -0.3750  0.1250 -1.8125 -1.1875 -0.3125 -1.5000 -2.0625
#> [226] -1.0625 -2.2500 -0.8125 -1.3125 -1.4375 -1.0625 -0.5625 -0.8750 -2.3750
#> [235] -3.8750 -0.8125 -1.1875 -1.3125  1.5000 -0.0625
residuals(mixed)
#>   [1] -2.333333e+00 -1.666667e+00 -3.666667e+00 -1.000000e+00  3.333333e-01
#>   [6]  1.387779e-15 -1.000000e+00  1.054712e-15 -1.333333e+00 -1.000000e+00
#>  [11] -2.333333e+00 -2.000000e+00 -6.666667e-01 -2.000000e+00 -3.000000e+00
#>  [16]  1.000000e+00  1.000000e+00  4.440892e-16 -5.551115e-17  1.333333e+00
#>  [21] -6.666667e-01 -3.053113e-16 -2.000000e+00  6.666667e-01  2.000000e+00
#>  [26] -3.333333e-01 -6.666667e-01 -6.666667e-01 -6.666667e-01  6.666667e-01
#>  [31] -2.000000e+00 -1.000000e+00 -1.000000e+00 -1.000000e+00 -1.666667e+00
#>  [36] -1.666667e+00 -3.000000e+00 -1.000000e+00 -2.333333e+00 -2.000000e+00
#>  [41] -1.333333e+00 -1.666667e+00 -1.666667e+00 -1.666667e+00 -3.333333e-01
#>  [46]  1.000000e+00  1.110223e-16  1.000000e+00  1.000000e+00  3.333333e-01
#>  [51]  2.333333e+00  3.000000e+00  3.000000e+00  1.666667e+00  2.220446e-16
#>  [56]  1.666667e+00  2.333333e+00  2.333333e+00  2.333333e+00 -3.333333e-01
#>  [61]  2.500000e-01 -2.500000e-01 -5.000000e-01  2.500000e+00  1.750000e+00
#>  [66] -1.500000e+00 -2.500000e-01 -1.000000e+00  1.000000e+00  5.000000e-01
#>  [71]  1.750000e+00  1.500000e+00  1.250000e+00  3.500000e+00  2.000000e+00
#>  [76] -7.500000e-01 -2.500000e-01 -5.000000e-01 -1.500000e+00 -3.250000e+00
#>  [81] -5.000000e-01 -2.500000e-01  2.109424e-16 -2.000000e+00 -3.500000e+00
#>  [86] -1.250000e+00 -1.500000e+00 -1.750000e+00 -3.500000e+00 -2.000000e+00
#>  [91]  2.500000e-01 -2.500000e-01 -5.000000e-01 -1.500000e+00  7.500000e-01
#>  [96]  5.000000e-01 -2.500000e-01  2.109424e-16  2.000000e+00  1.500000e+00
#> [101] -1.250000e+00 -1.500000e+00 -1.750000e+00 -5.000000e-01 -2.220446e-16
#> [106]  2.500000e-01  7.500000e-01  1.500000e+00  5.000000e-01  7.500000e-01
#> [111]  1.500000e+00  7.500000e-01  1.000000e+00 -1.000000e+00  1.500000e+00
#> [116]  7.500000e-01  1.500000e+00  2.250000e+00  5.000000e-01 -2.220446e-16
#> [121] -3.333333e-01  3.333333e-01  3.333333e-01 -1.000000e+00 -2.666667e+00
#> [126] -1.000000e+00 -1.000000e+00 -2.000000e+00  6.666667e-01  2.914335e-15
#> [131]  6.666667e-01  9.436896e-16  3.333333e-01 -1.000000e+00  4.440892e-16
#> [136]  2.666667e+00  1.333333e+00  3.333333e+00  2.000000e+00  2.333333e+00
#> [141]  1.000000e+00  2.000000e+00  2.000000e+00  6.666667e-01  1.000000e+00
#> [146]  1.666667e+00  2.000000e+00  3.333333e-01  3.000000e+00  3.000000e+00
#> [151]  5.551115e-16  5.000000e-01 -5.000000e-01 -5.000000e-01  5.000000e-01
#> [156] -2.000000e+00 -2.500000e+00 -2.500000e+00 -5.000000e-01  1.110223e-16
#> [161]  1.000000e+00  3.330669e-16  5.000000e-01  5.000000e-01  5.000000e-01
#> [166] -4.440892e-16 -5.000000e-01  5.000000e-01  5.000000e-01 -5.000000e-01
#> [171]  2.000000e+00  2.500000e+00  2.500000e+00  5.000000e-01 -2.775558e-16
#> [176] -1.000000e+00 -7.771561e-16 -5.000000e-01 -5.000000e-01 -5.000000e-01
#> [181]  5.000000e-01  5.000000e-01 -8.881784e-16 -1.221245e-15 -1.000000e+00
#> [186]  1.000000e+00  1.000000e+00  1.000000e+00 -1.000000e+00  5.000000e-01
#> [191]  1.000000e+00  1.500000e+00  5.000000e-01  2.500000e+00  2.000000e+00
#> [196] -5.000000e-01 -5.000000e-01  0.000000e+00  1.110223e-16  1.000000e+00
#> [201] -1.000000e+00 -1.000000e+00 -1.000000e+00  1.000000e+00 -5.000000e-01
#> [206] -1.000000e+00 -1.500000e+00 -5.000000e-01 -2.500000e+00 -2.000000e+00
#> [211]  5.000000e-01  1.000000e+00  4.440892e-16  5.551115e-16  1.000000e+00
#> [216] -1.000000e+00 -5.000000e-01  1.000000e+00  1.000000e+00  2.000000e+00
#> [221] -5.000000e-01  4.996004e-16  5.000000e-01 -1.500000e+00 -1.000000e+00
#> [226] -5.000000e-01 -1.000000e+00  4.440892e-16  5.551115e-16 -1.000000e+00
#> [231]  1.000000e+00  5.000000e-01 -1.000000e+00 -1.000000e+00 -2.000000e+00
#> [236]  5.000000e-01  4.996004e-16 -5.000000e-01  1.500000e+00  1.000000e+00
residuals(between)
#>  [1] -1.4444444 -0.4444444  1.8888889 -0.3333333  0.3333333  0.6666667
#>  [7] -0.6666667  0.1666667 -0.1666667  0.1111111 -1.5555556  1.4444444
#> [13]  0.8333333 -1.5000000 -0.1666667  0.8333333
residuals(between, append = TRUE) # since data was aggragated across within conditions
#>    id treatment gender .residuals.
#> 1   1   control      M  -1.4444444
#> 2   2   control      M  -0.4444444
#> 3   3   control      M   1.8888889
#> 4   4   control      F  -0.3333333
#> 5   5   control      F   0.3333333
#> 6   6         A      M   0.6666667
#> 7   7         A      M  -0.6666667
#> 8   8         A      F   0.1666667
#> 9   9         A      F  -0.1666667
#> 10 10         B      M   0.1111111
#> 11 11         B      M  -1.5555556
#> 12 12         B      M   1.4444444
#> 13 13         B      F   0.8333333
#> 14 14         B      F  -1.5000000
#> 15 15         B      F  -0.1666667
#> 16 16         B      F   0.8333333
```

<sup>Created on 2020-05-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by singmann** [comment]
That does look like a very good starting point. I have tried to add an argument  `"data_changed"` to `afex_aov` objects and added a corresponding warning to the `residuals` method, but could not add it to the pull request. Not sure if you did not allow me changing the pull request or I could not use github correctly, but my changes are now at the following link and should be incorporated: https://github.com/singmann/afex/tree/mattansb-master

Before accepting this, I would like to discuss a few more things and/or see the following changes:

- [ ] Add my changes to the pull request.
- [ ] With `lm`, the residuals function returns a named vector where the names correspond to the row names of the data frame. When returning a vector this function should do the same.
- [ ] `residuals.lm` has an additional `type` argument (see `?residuals.lm`) with possible values `("working", "response", "deviance", "pearson", "partial")`. It might makes sense to have at least some support for this as well, even if not all of those.
- [ ] The unit tests should test that whenever data is reordered or aggregated the warning is shown, but not if the original data is used. My additional examples provide a good start point for that. One could also fit the same model with `lm` to compare this as well. Another idea would be to check if the reordering really works.
- [ ] The reordering looks very general and could also be used as a basis for a `fitted` and `predict` function for `afex_aov` objects. Are you willing to s
- [ ] 
- 
- 
-

**Comment by mattansb** [comment]
I've done point 1, 3 (passed via `...`), 5, 6, 7.

I also think I've done 4 (unit tests) - let me know if you think anything should / could be added.

I also think I've done 2 - names are just taken from `rownames(object$data$long)`. Let me know if that's not what you meant.

Let me know what else (:

I think predict might be somewhat harder - for within/mixed models, users will expect `newdata` to be in the long format, but `predict.lm` in such cases will expect wide data. I suggest we leave this for another PR.

(I also think I added you to my fork now)

**Comment by singmann** [comment]
sorry for the delay. I added a check for the within example (i.e., the original order) and it still produced a warning. I fixed that though.

Thanks for the commit. Really nice work. If you want to add a `ggplot` method soon, let me know.

**Pull request merged**
