### PR TITLE
Adds sig_symbol support to mixed()-methods.

### PR DESCRIPTION
**Pull request by crsh**
Hi Henrik,

this pull request adds the support for sig_symbols to mixed() and related methods as discussed in #17.

Also, it
- adds unit tests for aov_car() and mixed()
- adds documentation updates
- changes default of nice.mixed() and anova.afex_aov() to sig_symbols-attribute of object

Let me know what you think.

### CODE REVIEW

**Comment by singmann** [comment]
The tests seems to fail, particularly `testthat/test-mixed-structure.R:291`.
Can you check that out?

**Comment by singmann** [comment]
Just to be clear what I mean, I am not concerned about the code/doc mismatch issues. Only the unit test problems (seems to be also `@test-mixed-structure.R#127`).

**Comment by crsh** [comment]
My bad, I thought I had run the checks before creating the pull request. One test was incorrect and I had to change the order arguments in `anova.mixed()`. I think it should work now (besides the code-doc-mismatches).

**Comment by singmann** [comment]
Thanks a lot. I will send you a mail once the new version of the package is on CRAN.

**Pull request merged**
