### PR TITLE
Attributes 'correction' and 'observed' for afex_aov$anova_table and detailed print method

### LINKED ISSUE #9: Observed and df correction attributes for nice data.frames
Hi Henrik,

I'm currently working on refining the support of `afex_aov` objects in my package `papaja`. It's already a pretty seamless integration, however, there are some redundancies for options that users set when calling `aov_car`. Some options have to be set again in `papaja` functions because there is no way of knowing the original parameters. As far as I can tell, it is, e.g., impossible to deduce how df were corrected in within-subject designs or which factors were observed.

What do you think about adding these parameters as attributes to the `anova_table` as I have done in my previous pull request with the `p.adjust.method`? I'd be happy to do this myself but I wanted to check with you first before getting started.

### PR DESCRIPTION
**Pull request by crsh**
Hi Henrik,

this is my second shot at the suggested addition of the attributes `correction` and `observed` to `anova_table` objects. The parameters of `nice.afex_aov()` default to the parameters set when calling `afex_aov()`, which again defaults to the options set in `afex_options()` (default of `anova.afex_aov()`). I have also fixed the backward compatibility issue so that everything should work with old `afex_aov` objects that lack the newly added attributes. I have added some tests in `test-aov-car-structural.R`. These changes resolve #9.

While I was at it, I used the new attributes to add a little more detail to the printed output for `afex_aov` objects and the `nice()`-output:

    Anova Table (Type 3 tests, bonferroni-adjusted)

    Response: rt
           Effect    df     MSE         F ges p.value
    1       angle 2, 18 3560.00 40.72 *** .34  <.0001
    2       noise  1, 9 8460.00 33.77 *** .25   .0008
    3 angle:noise 2, 18 1160.00 45.31 *** .12  <.0001

    Sphericity correction method: HF

The most straight forward way to accomplish this for both `afex_aov` and `nice()`-output, to me, was to define a new class `nice_table` and than have `print.afex_aov()` call `print.nice_table()`.

Let me know what you think.

### CODE REVIEW

**Comment by singmann** [comment]
Hi Frederik,

Took me some time over the holidays to look into it, but I will accept it as is. 

The package does actually not pass `devtools::check()` anymore after applying the patch you submitted, but the test that throws the error is basically wrong. To exemplify with an example from `aov_car`, the following two calls differ in the previous versions of `afex`, but should not. `nice()` on an `afex_aov` object should always return the same table as the initially specified anova. And your patch ensures this. Thanks.

```
# in old afex version
data(obk.long, package = "afex")
ex1 <- aov_car(value ~ treatment * gender + Error(id/(phase*hour)), 
        data = obk.long, observed = "gender")
ex1
##                         Effect          df   MSE         F  ges p.value
## 1                    treatment       2, 10 22.81    3.94 +  .20     .05
## 2                       gender       1, 10 22.81    3.66 +  .11     .08
## 3             treatment:gender       2, 10 22.81      2.86  .18     .10
## 4                        phase 1.60, 15.99  5.02 16.13 ***  .15   .0003
## 5              treatment:phase 3.20, 15.99  5.02    4.85 *  .10     .01
## 6                 gender:phase 1.60, 15.99  5.02      0.28 .003     .71
## 7       treatment:gender:phase 3.20, 15.99  5.02      0.64  .01     .61
## 8                         hour 1.84, 18.41  3.39 16.69 ***  .13  <.0001
## 9               treatment:hour 3.68, 18.41  3.39      0.09 .002     .98
## 10                 gender:hour 1.84, 18.41  3.39      0.45 .004     .63
## 11       treatment:gender:hour 3.68, 18.41  3.39      0.62  .01     .64
## 12                  phase:hour 3.60, 35.96  2.67      1.18  .02     .33
## 13        treatment:phase:hour 7.19, 35.96  2.67      0.35 .009     .93
## 14           gender:phase:hour 3.60, 35.96  2.67      0.93  .01     .45
## 15 treatment:gender:phase:hour 7.19, 35.96  2.67      0.74  .02     .65
nice(ex1)  # ges differs, but should probably be the same
##                         Effect          df   MSE         F  ges p.value
## 1                    treatment       2, 10 22.81    3.94 +  .28     .05
## 2                       gender       1, 10 22.81    3.66 +  .15     .08
## 3             treatment:gender       2, 10 22.81      2.86  .22     .10
## 4                        phase 1.60, 15.99  5.02 16.13 ***  .22   .0003
## 5              treatment:phase 3.20, 15.99  5.02    4.85 *  .14     .01
## 6                 gender:phase 1.60, 15.99  5.02      0.28 .005     .71
## 7       treatment:gender:phase 3.20, 15.99  5.02      0.64  .02     .61
## 8                         hour 1.84, 18.41  3.39 16.69 ***  .18  <.0001
## 9               treatment:hour 3.68, 18.41  3.39      0.09 .002     .98
## 10                 gender:hour 1.84, 18.41  3.39      0.45 .006     .63
## 11       treatment:gender:hour 3.68, 18.41  3.39      0.62  .02     .64
## 12                  phase:hour 3.60, 35.96  2.67      1.18  .02     .33
## 13        treatment:phase:hour 7.19, 35.96  2.67      0.35  .01     .93
## 14           gender:phase:hour 3.60, 35.96  2.67      0.93  .02     .45
## 15 treatment:gender:phase:hour 7.19, 35.96  2.67      0.74  .03     .65
``` 

Now they both return the same:
```
nice(ex1)
# after applying your patch.
## Anova Table (Type 3 tests)
## 
## Response: value
##                         Effect          df   MSE         F  ges p.value
## 1                    treatment       2, 10 22.81    3.94 +  .20     .05
## 2                       gender       1, 10 22.81    3.66 +  .11     .08
## 3             treatment:gender       2, 10 22.81      2.86  .18     .10
## 4                        phase 1.60, 15.99  5.02 16.13 ***  .15   .0003
## 5              treatment:phase 3.20, 15.99  5.02    4.85 *  .10     .01
## 6                 gender:phase 1.60, 15.99  5.02      0.28 .003     .71
## 7       treatment:gender:phase 3.20, 15.99  5.02      0.64  .01     .61
## 8                         hour 1.84, 18.41  3.39 16.69 ***  .13  <.0001
## 9               treatment:hour 3.68, 18.41  3.39      0.09 .002     .98
## 10                 gender:hour 1.84, 18.41  3.39      0.45 .004     .63
## 11       treatment:gender:hour 3.68, 18.41  3.39      0.62  .01     .64
## 12                  phase:hour 3.60, 35.96  2.67      1.18  .02     .33
## 13        treatment:phase:hour 7.19, 35.96  2.67      0.35 .009     .93
## 14           gender:phase:hour 3.60, 35.96  2.67      0.93  .01     .45
## 15 treatment:gender:phase:hour 7.19, 35.96  2.67      0.74  .02     .65
## 
## Sphericity correction method: GG 
```

I was initially a little bit unsure about the idea of adding another class (`nice_table`), but it still works very nicely as a `data.frame` and can be incorporated easily into reports:
```
knitr::kable(nice(ex1))
## 
## 
## |Effect                      |df          |MSE   |F         |ges  |p.value |
## |:---------------------------|:-----------|:-----|:---------|:----|:-------|
## |treatment                   |2, 10       |22.81 |3.94 +    |.20  |.05     |
## |gender                      |1, 10       |22.81 |3.66 +    |.11  |.08     |
## |treatment:gender            |2, 10       |22.81 |2.86      |.18  |.10     |
## |phase                       |1.60, 15.99 |5.02  |16.13 *** |.15  |.0003   |
## |treatment:phase             |3.20, 15.99 |5.02  |4.85 *    |.10  |.01     |
## |gender:phase                |1.60, 15.99 |5.02  |0.28      |.003 |.71     |
## |treatment:gender:phase      |3.20, 15.99 |5.02  |0.64      |.01  |.61     |
## |hour                        |1.84, 18.41 |3.39  |16.69 *** |.13  |<.0001  |
## |treatment:hour              |3.68, 18.41 |3.39  |0.09      |.002 |.98     |
## |gender:hour                 |1.84, 18.41 |3.39  |0.45      |.004 |.63     |
## |treatment:gender:hour       |3.68, 18.41 |3.39  |0.62      |.01  |.64     |
## |phase:hour                  |3.60, 35.96 |2.67  |1.18      |.02  |.33     |
## |treatment:phase:hour        |7.19, 35.96 |2.67  |0.35      |.009 |.93     |
## |gender:phase:hour           |3.60, 35.96 |2.67  |0.93      |.01  |.45     |
## |treatment:gender:phase:hour |7.19, 35.96 |2.67  |0.74      |.02  |.65     |
```

The only thing I am still a little unsure about is the inconsistency in the empty attributes. For `correction` and `p.adjust.method` it is `"none"`, whereas for `observed` it is `character(0)`. Why not make it the same for all three (e.g., `character(0)`)?

**Comment by crsh** [comment]
Hi Henrik,

thanks for the detailed feedback. I settled on `"none"` for `p.adjust.method` because it is consistent with the behavior of base functions, such as `pairwise.t.test()`. It then seemed consistent to adopt the same behavior for `correction`. As you may remember from my previous pull request, `"none"` does not work for `observed` so I had to go with something else here. `character(0)` appeared to be a straight forward solution to me.

**Comment by singmann** [comment]
Thanks. That explains this. 

If you have more suggestions or ideas for new features I am always happy to discuss them. you might have seen, I also added you as an author to the package (your status was contributor before).

**Comment by crsh** [comment]
Wow, thank you. Much appreciated.

**Pull request merged**
